# Generated by Django 3.2.16 on 2025-03-20 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_category'),
        ('blog', '0005_comment'),
    ]

    operations = [
    ]
